accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

booksphile/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include(('libstore.urls', 'libstore'), namespace='libstore')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libstore/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.library, name='library'),
    path('books/<slug:slug>/', views.shelf, name='book_details'),
    path('createBook', views.create_book, name='create_book'),
    
]

accounts/models.py
from django.db import models

# Create your models here.

libstore/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class library_manager(models.Model):
    topic_title = models.CharField(max_length=15, null=True)
    slug = models.SlugField(null=True)
    date = models.DateField(auto_now_add=True)
    overview = models.TextField(null=True) 
    img =  models.ImageField(default='default.png', blank=True , null=True)
    stored_file = models.FileField(default='default.pdf', blank=True , null=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.topic_title

libstore/forms.py
from django import forms
from . import models

class Createlib(forms.ModelForm):
    class Meta:
        model = models.library_manager
        fields = ['topic_title' , 'slug' , 'overview' , 'img' ,'stored_file']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout 

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('libstore:library')
    else:
        form = UserCreationForm
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('libstore:library')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

booksphile/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models

libstore/views.py
from .models import library_manager
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

app_name = 'libstore'

@login_required(login_url='/accounts/login/')
def library(request):
    books = library_manager.objects.all()
    context = {'book': books}
    return render(request, 'libstore/library.html', context)

@login_required(login_url='/accounts/login/')
def shelf(request,slug):
    book = library_manager.objects.get(slug=slug)
    return render(request, 'libstore/detailed_book.html', {'book': book})

@login_required(login_url='/accounts/login')
def create_book(request):
    if request.method == 'POST':
        form = forms.Createlib(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()

            return redirect('libstore:library')
    else:
        form = forms.Createlib()
    return render(request, 'libstore/createBook.html', {'form': form})

@login_required(login_url='accounts/login')
def download(request,file_name):
    
    f = library_manager.objects.get(stored_file=file_name)

    

accounts/templates/accounts/login.html
{% extends 'basic_layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
 
  <div class="form-group d-flex justify-content-center align-items-center mt-5" width="40px">
    <form action="{% url 'accounts:login' %}" method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-info" value="LogIn">
        <p class="ml-1"><a href="{% url 'accounts:signup' %}">signup</a></p>
    </form>
    
</div>
    
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'basic_layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form-group d-flex justify-content-center align-items-center mt-5">
    <form action="{% url 'accounts:signup' %}" method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-info" value="Sign Up">
        <p><a href="{% url 'accounts:login' %}">Back to login</a></p>
    </form>
</div>
{% endblock %}

libstore/templates/libstore/createBook.html
{% extends 'basic_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<header>
    <nav class="navbar navbar-dark bg-primary">
        <a href="{% url 'libstore:library' %}" class="btn btn-warning mr-sm-2"> Back </a></p>
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger"> Log out </button>
        </form>

    </nav>
</header>

<h3 class="Display-4 mr-3 ml-3 mt-2"> Create a Book </h3>

<p class="h5 mr-3 ml-3 mb-5">(with review page and the pdf file here)</p>

<div class="form-group mr-5 ml-5">

    <form class="{url 'libstore:create_book' }" method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.topic_title|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.slug|as_crispy_field }}
            </div>
        </div>
        <div>
            {{form.overview|as_crispy_field}}
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.img|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.stored_file|as_crispy_field }}
            </div>
        </div>
        <input type="submit" class="btn btn-success" value="Create">

    </form>

</div>

{% endblock %}

libstore/templates/libstore/detailed_book.html
{% extends 'basic_layout.html' %}

{% block content %}

<header>
    <nav class="navbar navbar-dark bg-primary mb-3">
        <a href="{% url 'libstore:library' %}" class="btn btn-warning mr-sm-2"> Back </a></p>
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger"> Log out </button>
        </form>

    </nav>
</header>
<div class="container border border-primary">
    <div class="row ml-2">
        <p class="h3"> {{ book.topic_title }} </p>
    </div>
    <div class="row ml-2">
        <p> {{ book.date }} </p>
    </div>
    <div class="row ml-2 mr-2 mb-2 border border-dark">
        <img src="{{ book.img.url }}" class="img-fluid" alt="Responsive image"/>
    </div>
</div>

{% if book.stored_file != null %}
<div class="pull-right mt-2 ml-2">
<p> file size : {{ book.stored_file.size }} </p>
<a href="/media/{{book.stored_file.name}}" download>Download</a>
</div>
{% endif %}

{% endblock %}

libstore/templates/libstore/library.html
{% extends 'basic_layout.html' %}

{% block content %}

<header>
    <nav class="navbar navbar-dark bg-primary">

        <div class="mr-sm-2">
            <a href="{% url 'libstore:create_book' %}" class="btn btn-success"> create an awesome book </a>
        </div>
        <div class="my-2 my-sm-0">
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-success " type="submit"> Log out </button>
        </form>
    </div>
    </nav>
</header>
<div class="container mt-3">
    {% for bk in book %}
    <div class="card border-dark mb-3 inline-block" style="max-width: 18rem;">
        <img class="card-img-top" src="/media/{{bk.img}}" height="100px" width="10px" alt="Card image cap">
        <div class="card-body">
            <h3 class="display-4"> <a class="card-link" href="{% url 'libstore:book_details' slug=bk.slug %}">
                    {{ bk.topic_title }} </a></h3>
            <h5 class="card-text"> {{ bk.slug }} </h3>
                <p class="card-subtitle mb-2 text-muted"> {{ bk.date }} </p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/basic_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="body" >

    {% block content %}
        
    {% endblock %}
</body>
</html>